project:
  type: website
  output-dir: docs

website:
  title: "Josh Cullen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: lux
      dark: solar
    css: styles.css
    toc: true
    page-layout: full