project:
  type: website
  output-dir: docs

website:
  title: "Josh Cullen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: Publications/index.qmd
        text: Publications
      - href: Research/index.qmd
        text: Research
  page-footer: "Copyright 2023, Josh Cullen"
  cookie-consent:
    type: express
    style: headline
    palette: dark
  google-analytics:
    tracking-id: "G-4NW3SGHKV5"
    anonymize-ip: true

format:
  html:
    theme: 
      light: lux
      dark: solar
    css: styles.css
    toc: true
    page-layout: full